### ISSUE TITLE
Using parameterized functions for boundary conditions

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaDiffEq/ParameterizedFunctions.jl#33]
I got a problem, where the boundary conditions depend on parameters also.
Can I use the '@ode_def' macro also?

**Comment by ChrisRackauckas** [comment]
As talked about in the chatroom, if you use a BVP solver with `Shooting` or `GeneralMIRK`

http://docs.juliadiffeq.org/latest/tutorials/bvp_example.html#Boundary-Condition-1

then you have access to the time values because the current solution, either written there as `u` or `sol`, has the values in `u.t` or `sol.t`.

**Comment by ChrisRackauckas** [comment]
Why did I talk about time? If you're looking for the parameters, it's `sol.prob.f.S` or however you named the parameters (or `sol.prob.f.params` if it's a non-macro version).

**Comment by ChrisRackauckas** [comment]
This is handled via the problem types directly.
