### ISSUE TITLE
Reserved names

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaDiffEq/ParameterizedFunctions.jl#34]
Users should be noticed not to used the reserved names `u`, `du`, `p` and `t`.

Changing these names to something less frequently used could be also helpful.

**Comment by ChrisRackauckas** [comment]
`u`, `du`, and `p` are now internally changed to `___u`, `___du`, and `___p` which shouldn't ever clash (who uses three underscores?). `t` is different: the user needs to interact with that one unless they use the `ode_def_opts` function to change the name of the dependent variable. I am not sure how to fix that and make the name choice available to the macro without a breaking change to the syntax. I'll tag what I have now though since that's a big improvement already.

**Comment by BeastyBlacksmith** [comment]
Would it be possible to display a warning, if `t`  is used, that it is bound to the dependent variable and shouldn't be used otherwise?

**Comment by ChrisRackauckas** [comment]
Yes, I could do that.

**Comment by ChrisRackauckas** [comment]
The warning was added.
